package astraeus.game.task;

public enum TaskType {
	CURRENT_ACTION,
	TELEPORTING,
	SPECIAL_RESTORE,
	COMBAT,
	SEQUENTIAL_MINIGAME,
	LOOSE_TARGET,
	FISHING,
	WOODCUTTING,
	MINING,
	COOKING,
	MINIGAME,
	OBJECT_REPLACEMENT;
}